sudo: required
dist: trusty

language: d

os:
  - linux
  - osx

env:
  - ARCH=x86_64 CONFIG=default
  - ARCH=x86_64 CONFIG=minimal
  - ARCH=x86_64 CONFIG=console
  - ARCH=x86 CONFIG=default
  - ARCH=x86 CONFIG=minimal
  - ARCH=x86 CONFIG=console

d:
  - dmd
  - dmd-beta
  - ldc

# No-one cares about OS X x86
matrix:
  exclude:
    - os: osx
      env: ARCH=x86 CONFIG=default
    - os: osx
      env: ARCH=x86 CONFIG=minimal
    - os: osx
      env: ARCH=x86 CONFIG=console
    - os: osx
      env: ARCH=x86_64 CONFIG=console
    - os: osx
      env: ARCH=x86_64 CONFIG=minimal

# Sort out packages
install:
  - |
    if [ $TRAVIS_OS_NAME == osx ]
    then
      brew update
      brew install sdl2
    elif [ $TRAVIS_OS_NAME == linux ]
    then
      if [ $ARCH == x86 ]
      then
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib libgl1-mesa-glx-lts-utopic:i386 libfreetype6:i386 libsdl2-2.0-0:i386 zlib1g-dev:i386
      else
        sudo apt-get update
        sudo apt-get install -y libfreetype6 libsdl2-2.0-0 zlib1g-dev
      fi
    fi
#libgl1-mesa-glx:i386

# Start a virtual x-server.
before_script:
  - |
    if [ $TRAVIS_OS_NAME == linux ]
    then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
    fi

script:
  - dub test --compiler=${DC} --arch=${ARCH} --config=${CONFIG}
